version: '3.7'
# This is the Docker-Compose orchestration of LORIS WITHOUT MRI component pre-configured (i.e. base image)
# This version does rely on the image from DockerHub and is a LOCAL BUILD
# Last updated: 2019-01-13 12:15
# Maintainer: Yang Ding (it@cnbp.ca)

services:

    # This is the database behind the LORIS 22 instance: note all data are stored in the dockerfile
    lorisdb:

         #volumes:
         #    - //c/git/data:/var/lib/mysql
        build:
            context: ../..
            dockerfile:  DockerBuilds/22/Dockerfile.LORIS${LORIS_version}.db
            # make sure these variables are properly named in the .env files: e.g .PlaceHolderRootPassword
            args:
                - ARGS_MYSQL_ROOT_PASSWORD=${MySQLRootPassword}
            # Environment not specified as the DockerFile is suppose to be standalone and workable too .
        networks:
             - backend
        ports:
            - "${Port_MySQL}:3306"

        # Container name and label
        #container_name: LORIS_MySQLDB_${tag}
        image: neonatalbrainplatform/lorisdb:${LORIS_version}

        # Reducing logging clutter
        logging:
            driver: "none"


    # The loris frontned is HARDCODED to be recognized in subroutines as "loris" DO NOT CHANGE THIS NAME.
    loris:
         # Container name and label
        #container_name: LORIS_${tag}

        # Building instructions.
        build:
            context: ../..
            dockerfile: DockerBuilds/22/Dockerfile.LORIS${LORIS_version}.Ubuntu18
            args:
                - ARGS_ProjectName=${ProjectName}
                - ARGS_MySQLHost=${MySQLHost}
                - ARGS_MySQLUser=${MySQLUser}
                - ARGS_MySQLUserPassword=${MySQLUserPassword}
                - ARGS_MySQLDatabase=LORIS
                - ARGS_LorisMaintenanceEmail=${LorisMaintenanceEmail}

        # Where to push eventually.
        image: neonatalbrainplatform/loris:${LORIS_version}

        networks:
            - backend
        depends_on:
            - lorisdb
        ports:
            - "${Port_LORIS_HTTP}:80"
            - "${Port_LORIS_HTTPS}:443"

     # This is the selenium image (i.e. worker node) that will run the actual work process which is executed to setup the bridge connection between the database and the front end user interaction
    chrome:
        image: selenium/node-chrome-debug:3.14.0-gallium
        volumes:
          - /dev/shm:/dev/shm
        depends_on:
          - hub
          - loris
          - lorisdb
        environment:
          HUB_HOST: hub
          HUB_PORT: 4444
        entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
        networks:
          - backend

    # The hub is HARDCODED to be recognized in subroutines as "hub" DO NOT CHANGE THIS NAME.
    hub:
        image: selenium/hub:3.14.0-gallium
        depends_on:
            - loris
            - lorisdb
        ports:
            - "4444:4444"
        networks:
            - backend

    lorisdbsetup:

        build:
            context: ../..
            dockerfile: DockerBuilds/22/Dockerfile.LORIS${LORIS_version}.dbsetup
            args:
                - ARGS_MySQLHost=${MySQLHost}
                - ARGS_MySQLRoot=${MySQLRoot}
                - ARGS_MySQLRootPassword=${MySQLRootPassword}
                - ARGS_MySQLUser=${MySQLUser}
                - ARGS_MySQLUserPassword=${MySQLUserPassword}
                - ARGS_LorisFrontendUser=${LorisFrontendUser}
                - ARGS_LorisFrontendPassword=${LorisFrontendPassword}
                - ARGS_Port_LORIS_HTTP=${Port_LORIS_HTTP}
                - ARGS_LorisMaintenanceEmail=${LorisMaintenanceEmail}
                - ARGS_LORIS21=LORIS # the database created by default is called LORIS
            # Environment not specified as the DockerFile is suppose to be standalone and workable too .
        # Where to push eventually.
        image: neonatalbrainplatform/lorisdbsetup:${LORIS_version}

        stdin_open: true
        tty: true
        ports:
          - "5900-5999:5900"
        depends_on: # all these need to be up and running before running the Selenium integrator.
          - loris
          - lorisdb
          - hub
          - chrome
        networks:
            - backend

# Networks allow connection with EXTERNAL containers and PROJECTS
networks:
  backend:
    driver: "bridge"

# To run:
# docker-compose -f ComposeLORIS22.0.0.yml --force
