FROM mysql:5.7

# These are placeholder password overwritten by the environment shortly.
ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_DATABASE database
ENV MYSQL_USER root
ENV MYSQL_PASSWORD mysql007
ENV COMPOSE_CONVERT_WINDOWS_PATHS 1

# COPY init.sql /docker-entrypoint-initdb.d/
# RUN chmod a+x /docker-entrypoint-initdb.d/init.sql && chown root:root     /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306
CMD ["mysqld"]

# Build:
# docker build --build-arg http_proxy=<value> --build-arg https_proxy=<value> -f Dockerfile.LORIS22.MySQLDB -t dyt811:LORIS22MySQLDB .
# Run:

