FROM selenium/node-chrome:3.14.0

# install Python 3.7
RUN sudo apt-get update
RUN sudo apt-get install -y software-properties-common
RUN sudo add-apt-repository -y ppa:deadsnakes/ppa
RUN sudo sudo apt-get install -y python3

# First page configuraiton variables.

# Set default value while let people access these externally.
ARG ARGS_LorisMySQLHost=DefaultLorisMySQLHost
ENV LorisMySQLHost ${ARGS_LorisMySQLHost}

ARG ARGS_LorisMySQLRoot=DefaultLorisMySQLRoot
ENV LorisMySQLRoot ${ARGS_LorisMySQLRoot}

ARG ARGS_LorisMySQLRootPassword=DefaultLorisMySQLRootPassword
ENV LorisMySQLRootPassword ${ARGS_LorisMySQLRootPassword}
# Set the env based on the value of the arguments.




# Second page configuraiton variables.
# Set default value while let people access these externally.
ARG ARGS_LorisMySQLUser=DefaultLorisMySQLUser
ENV LorisMySQLUser ${ARGS_LorisMySQLUser}

ARG ARGS_LorisMySQLUserPassword=DefaultLorisMySQLUserPassword
ENV LorisMySQLUserPassword ${ARGS_LorisMySQLUserPassword}

ARG ARGS_LorisFrontendUser=DefaultLorisFrontendUser
ENV LorisFrontendUser ${ARGS_LorisFrontendUser}

ARG ARGS_LorisFrontendPassword=DefaultLorisFrontendPassword
ENV LorisFrontendPassword ${ARGS_LorisFrontendPassword}

ARG ARGS_Port_LORIS_HTTP=DefaultPort_LORIS_HTTP
ENV Port_LORIS_HTTP ${ARGS_Port_LORIS_HTTP}

# Set the env based on the value of the arguments.
ARG ARGS_LORIS22=DefaultLORIS22
ENV LORISURL ${ARGS_LORIS22}


COPY DockerBuilds/requirements.txt /setup/requirements.txt
COPY DockerBuilds/LORISDBSetup.py /setup/LORISDBSetup.py

# Setup
USER root

# Install pip
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

# Install requirements for selenium
RUN python3 -m pip install -r /setup/requirements.txt

# Setup LORIS using the script.
CMD python3 /setup/LORISDBSetup.py

